### PR TITLE
Fixup REPORT_LOCATION_ARGS to use positive length RT 132163

### PR DESCRIPTION
**Pull request by atoomic**
Use vFAIL instead of vFAIL2, and adjust the length
when the offset is negative.

https://rt.perl.org/Public/Bug/Display.html?id=132163

### CODE REVIEW

**Comment by toddr** [comment]
@atoomic Please update the committer in these commits and force push the branch

```
Test Summary Report
-------------------
porting/authors.t                                                (Wstat: 0 Tests: 11 Failed: 1)
  Failed test:  6

**Comment by atoomic** [comment]
```
> git show --pretty=full
commit 45364a6dd368d2120ca62f88e2111e373d268ff7 (HEAD -> devel/rt-132163, perl5demo/devel/rt-132163, gh/devel/rt-132163)
Author: Nicolas R <atoomic@cpan.org>
Commit: Nicolas R <atoomic@cpan.org>

    Add unit test for RT #132163
```

**Comment by atoomic** [comment]
need to check with last blead changes it's still an issue
if so then rebase and resubmit

**Comment by atoomic** [comment]
cannot reproduce the problem with v5.27.5-349-gb9a5a78fe9

**Pull request closed without merging**
