### PR TITLE
Speed up Carp.pm when backtrace arguments are references

### PR DESCRIPTION
**Pull request by atoomic**
Avoid downgrading the string when not required.

Author: J. Nick Koston <nick@cpanel.net>
References: CPANEL-15140

### CODE REVIEW

**Comment by atoomic** [comment]
also one error from porting/authors.t
```
Test Summary Report
-------------------
porting/authors.t                                                (Wstat: 0 Tests: 23 Failed: 1)
  Failed test:  14
```

**Comment by atoomic** [comment]
merged to blead

**Comment by atoomic** [comment]
was merged to blead but then reverted by commit 0ebeacdece

**Comment by toddr** [comment]
Merged and reverted. See 7a831b721c469aeccfe1110a2d177dd115d5998d

**Pull request closed without merging**
